"""Settings for simulated annealing."""

ALPHA_BALANCE = 0.15
CONSTRUCTION_ITERATIONS = 44

SA_INITIAL_TEMP = 483.8485
SA_COOLING_RATE = 0.9211
SA_ITERATIONS_PER_TEMP = 84
SA_MIN_TEMP = 1e-3
SA_MAX_NEIGHBOR_ATTEMPTS = 250

NEIGHBORHOOD_WEIGHTS = {
    "relocate_best": 1.0,
    "remove_reinsert_three": 1.0,
}