"""Settings for simulated annealing tuning with Optuna."""

TUNING_INSTANCE_NAMES = ["K", "J"]
TUNING_SEEDS = [11, 22]

TUNING_TIME_LIMIT_SECONDS = 60
OPTUNA_N_TRIALS = 20 
OPTUNA_STUDY_NAME = "sa_tuning"

# Search ranges
INITIAL_TEMP_MIN = 20.0
INITIAL_TEMP_MAX = 500.0

COOLING_RATE_MIN = 0.90
COOLING_RATE_MAX = 0.999

ITERATIONS_PER_TEMP_MIN = 10
ITERATIONS_PER_TEMP_MAX = 150

CONSTRUCTION_ITERATIONS_MIN = 1
CONSTRUCTION_ITERATIONS_MAX = 75