"""Settings for simulated annealing tuning with Optuna."""

TUNING_INSTANCE_NAMES = ["K", "J", "F"]
TUNING_SEEDS = [11, 22, 33]

TUNING_TIME_LIMIT_SECONDS = 30.0

OPTUNA_N_TRIALS = 40
OPTUNA_N_JOBS = 4
OPTUNA_STUDY_NAME = "sa_tuning"
OPTUNA_SEED = 42
OPTUNA_RESET_STUDY = True

# Search ranges for the first tuning pass.
INITIAL_TEMP_MIN = 20.0
INITIAL_TEMP_MAX = 500.0

COOLING_RATE_MIN = 0.90
COOLING_RATE_MAX = 0.999

ITERATIONS_PER_TEMP_MIN = 10
ITERATIONS_PER_TEMP_MAX = 150

CONSTRUCTION_ITERATIONS_MIN = 1
CONSTRUCTION_ITERATIONS_MAX = 75