"""Settings for HGS tuning with Optuna."""

TUNING_INSTANCE_NAMES = ["D", "G", "I","K"]
TUNING_SEEDS = [11, 22, 33]

TUNING_TIME_LIMIT_SECONDS = 30.0

OPTUNA_N_TRIALS = 30
OPTUNA_N_JOBS = 4
OPTUNA_STUDY_NAME = "hgs_tuning"
OPTUNA_SEED = 42
OPTUNA_RESET_STUDY = True

POPULATION_SIZE_MIN = 6
POPULATION_SIZE_MAX = 14

ELITE_SIZE_MIN = 1
ELITE_SIZE_MAX = 4

TOURNAMENT_SIZE_MIN = 2
TOURNAMENT_SIZE_MAX = 4

INITIAL_INDIVIDUAL_TIME_MIN = 0.5
INITIAL_INDIVIDUAL_TIME_MAX = 2.0

OFFSPRING_IMPROVEMENT_TIME_MIN = 0.2
OFFSPRING_IMPROVEMENT_TIME_MAX = 1.0

PARENT1_ROUTE_INHERIT_PROB_MIN = 0.3
PARENT1_ROUTE_INHERIT_PROB_MAX = 0.8

PERTURBATION_STEPS_MIN = 1
PERTURBATION_STEPS_MAX = 4

CONSTRUCTION_ITERATIONS_MIN = 10
CONSTRUCTION_ITERATIONS_MAX = 60