"""Settings for iterated local search tuning with Optuna."""

TUNING_INSTANCE_NAMES = ["D", "G", "I","K"]
TUNING_SEEDS = [11, 22, 33]

TUNING_TIME_LIMIT_SECONDS = 30.0

OPTUNA_N_TRIALS = 30
OPTUNA_N_JOBS = 4
OPTUNA_STUDY_NAME = "ils_tuning"
OPTUNA_SEED = 42
OPTUNA_RESET_STUDY = True

PERTURBATION_STEPS_MIN = 1
PERTURBATION_STEPS_MAX = 20

CONSTRUCTION_ITERATIONS_MIN = 40
CONSTRUCTION_ITERATIONS_MAX = 100